# Generated by Django 5.2.16 on 2026-07-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('defect_image', models.ImageField(blank=True, null=True, upload_to='defects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspection')),
            ],
        ),
    ]
