# Generated by Django 5.2.16 on 2026-07-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('overall_condition', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection')),
            ],
        ),
    ]
